name: blind_nav_cam
description: MVP Flutter app to display live camera feed for assistive navigation
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.0
  http: ^1.2.0
  livekit_client: ^2.0.0

  # Camera access (Android + iOS)
  camera: ^0.11.0+2
  record: ^5.0.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
