name: blind_nav_cam
description: MVP Flutter app to display live camera feed for assistive navigation
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.0
  flutter_compass: ^0.8.1
  http: ^1.2.0
  livekit_client: ^2.0.0
  google_generative_ai: ^0.4.7
  dart_jsonwebtoken: ^3.3.1

  # Camera access (Android + iOS)
  camera: ^0.11.0+2
  record: ^6.0.0
  path_provider: ^2.1.0
  shared_preferences: ^2.2.0
  flutter_tts: ^4.2.5
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/

# Run "dart run flutter_launcher_icons" after adding/changing the icon image
flutter_launcher_icons:
  android: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"
